export const goodCorePersonalValues = [
  'honesty',
  'integrity',
  'responsibility',
  'accountability',
  'discipline',
  'empathy',
  'compassion',
  'respect',
  'loyalty',
  'fairness',
  'humility',
  'gratitude',
  'courage',
  'growth mindset',
  'curiosity',
  'perseverance',
  'independence',
  'collaboration',
  'patience',
  'open-mindedness',
  'transparency',
  'reliability',
  'self-awareness',
  'generosity',
  'optimism',
];

export const badCorePersonalValues = [
  'dishonesty',
  'manipulation',
  'arrogance',
  'egoism',
  'narcissism',
  'laziness',
  'cowardice',
  'dishonesty',
  'disrespect',
  'intolerance',
  'greed',
  'jealousy',
  'envy',
  'selfishness',
  'impulsiveness',
  'irresponsibility',
  'inconsistency',
  'deceitfulness',
  'close-mindedness',
  'aggressiveness',
  'toxicity',
  'entitlement',
  'recklessness',
  'exploitation',
  'hypocrisy',
];

export const allCorePersonalValues = [...goodCorePersonalValues, ...badCorePersonalValues];
